#!/bin/bash

# ----------------------- ANALYZE DATA ------------------------

# Analyze VITRO_DISH_TREAT_C_2D data
# python abm_analyze.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/PKLS/ --analyze --saveLoc D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/ANALYZED/
# python abm_analyze.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/PKLS/ --environment --saveLoc D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/ENVIRONMENT/
# python abm_analyze.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/PKLS/ --spatial --saveLoc D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/SPATIAL/
# python abm_lysis.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/LYSIS/ --saveLoc D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/LYSED/

# Analyze VITRO_DISH_TREAT_CH_2D data
# python abm_analyze.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/PKLS/ --analyze --saveLoc D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/ANALYZED/
# python abm_analyze.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/PKLS/ --environment --saveLoc D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/ENVIRONMENT/
# python abm_analyze.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/PKLS/ --spatial --saveLoc D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/SPATIAL/
# python abm_lysis.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/LYSIS/ --saveLoc D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/LYSED/

# Analyze VIVO_TISSUE_TREAT_CH_2D data
# python abm_analyze.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/PKLS/ --analyze --saveLoc D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/ANALYZED/
# python abm_analyze.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/PKLS/ --environment --saveLoc D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/ENVIRONMENT/
# python abm_analyze.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/PKLS/ --spatial --saveLoc D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/SPATIAL/
# python abm_lysis.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/LYSIS/ --saveLoc D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/LYSED/

# ----------------------- SUBSET DATA ------------------------

# Subset VITRO_DISH_TREAT_C_2D data
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/ANALYZED/ VITRO_DISH_TREAT_C_2D ANALYZED D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000)];[("TREAT RATIO":50-50),("DOSE":500)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/ENVIRONMENT/ VITRO_DISH_TREAT_C_2D ENVIRONMENT D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000)];[("TREAT RATIO":50-50),("DOSE":500)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/SPATIAL/ VITRO_DISH_TREAT_C_2D SPATIAL D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000)];[("TREAT RATIO":50-50),("DOSE":500)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/LYSED/ VITRO_DISH_TREAT_C_2D LYSED D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000)];[("TREAT RATIO":50-50),("DOSE":500)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/ANALYZED/ VITRO_DISH_TREAT_C_2D ANALYZED D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_C_2D/DATA/SUBSETS/ --states

# Subset VITRO_DISH_TREAT_CH_2D data
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/ANALYZED/ VITRO_DISH_TREAT_CH_2D ANALYZED D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":0)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/ANALYZED/ VITRO_DISH_TREAT_CH_2D ANALYZED D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":100)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/ENVIRONMENT/ VITRO_DISH_TREAT_CH_2D ENVIRONMENT D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":0)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/ENVIRONMENT/ VITRO_DISH_TREAT_CH_2D ENVIRONMENT D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":100)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/SPATIAL/ VITRO_DISH_TREAT_CH_2D SPATIAL D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":0)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/SPATIAL/ VITRO_DISH_TREAT_CH_2D SPATIAL D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":100)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/LYSED/ VITRO_DISH_TREAT_CH_2D LYSED D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":0)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/LYSED/ VITRO_DISH_TREAT_CH_2D LYSED D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":100)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/ANALYZED/ VITRO_DISH_TREAT_CH_2D ANALYZED D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/SUBSETS/ --states
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/ANALYZED/ VITRO_DISH_TREAT_CH_2D ANALYZED D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VITRO_DISH_TREAT_CH_2D/DATA/SUBSETS/ --states --subset [("ANTIGENS HEALTHY":100)]

# Subset VIVO_TISSUE_TREAT_CH_2D data
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/ANALYZED/ VIVO_TISSUE_TREAT_CH_2D ANALYZED D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":0)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/ANALYZED/ VIVO_TISSUE_TREAT_CH_2D ANALYZED D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":100)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/ENVIRONMENT/ VIVO_TISSUE_TREAT_CH_2D ENVIRONMENT D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":0)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/ENVIRONMENT/ VIVO_TISSUE_TREAT_CH_2D ENVIRONMENT D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":100)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/SPATIAL/ VIVO_TISSUE_TREAT_CH_2D SPATIAL D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":0)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/SPATIAL/ VIVO_TISSUE_TREAT_CH_2D SPATIAL D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":100)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/LYSED/ VIVO_TISSUE_TREAT_CH_2D LYSED D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":0)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":0)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":0)]
# python abm_subset.py D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/LYSED/ VIVO_TISSUE_TREAT_CH_2D LYSED D:/Users/Alex/Documents/Northwestern/Research/ABM/Output/VIVO_TISSUE_TREAT_CH_2D/DATA/SUBSETS/ --subset [("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("CAR AFFINITY":1e-7),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("DOSE":500),("TREAT RATIO":50-50),("CAR AFFINITY":1e-7),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("ANTIGENS CANCER":1000),("ANTIGENS HEALTHY":100)];[("TREAT RATIO":50-50),("DOSE":500),("ANTIGENS HEALTHY":100)]

# ----------------------- PLOT DATA ------------------------

# Plot VITRO_DISH_TREAT_C_2D data
# python abm_plot.py D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_C_2D\DATA\SUBSETS\ANALYZED\ --color "X" --saveLoc D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_C_2D\FIGURES\ANALYZED\
# python abm_plot.py D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_C_2D\DATA\SUBSETS\ENVIRONMENT\ --color "X" --saveLoc D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_C_2D\FIGURES\ENVIRONMENT\
# python abm_plot.py D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_C_2D\DATA\SUBSETS\SPATIAL\ --color "X" --saveLoc D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_C_2D\FIGURES\SPATIAL\
# python abm_plot.py D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_C_2D\DATA\SUBSETS\LYSED\ --color "X" --saveLoc D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_C_2D\FIGURES\LYSED\

# Plot VITRO_DISH_TREAT_CH_2D data
# python abm_plot.py D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_CH_2D\DATA\SUBSETS\ANALYZED\ --color "X" --saveLoc D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_CH_2D\FIGURES\ANALYZED\
# python abm_plot.py D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_CH_2D\DATA\SUBSETS\ENVIRONMENT\ --color "X" --saveLoc D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_CH_2D\FIGURES\ENVIRONMENT\
# python abm_plot.py D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_CH_2D\DATA\SUBSETS\SPATIAL\ --color "X" --saveLoc D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_CH_2D\FIGURES\SPATIAL\
# python abm_plot.py D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_CH_2D\DATA\SUBSETS\LYSED\ --color "X" --saveLoc D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_CH_2D\FIGURES\LYSED\

# Plot VIVO_TISSUE_TREAT_CH_2D data
# python abm_plot.py D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VIVO_TISSUE_TREAT_CH_2D\DATA\SUBSETS\ANALYZED\ --color "X" --saveLoc D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VIVO_TISSUE_TREAT_CH_2D\FIGURES\ANALYZED\
# python abm_plot.py D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VIVO_TISSUE_TREAT_CH_2D\DATA\SUBSETS\ENVIRONMENT\ --color "X" --saveLoc D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VIVO_TISSUE_TREAT_CH_2D\FIGURES\ENVIRONMENT\
# python abm_plot.py D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VIVO_TISSUE_TREAT_CH_2D\DATA\SUBSETS\SPATIAL\ --color "X" --saveLoc D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VIVO_TISSUE_TREAT_CH_2D\FIGURES\SPATIAL\
# python abm_plot.py D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VIVO_TISSUE_TREAT_CH_2D\DATA\SUBSETS\LYSED\ --color "X" --saveLoc D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VIVO_TISSUE_TREAT_CH_2D\FIGURES\LYSED\

# ----------------------- STATS DATA ------------------------

python abm_stats.py D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_C_2D\DATA\SUBSETS\ANALYZED\VITRO_DISH_TREAT_C_2D_X_X_X_X_NA_STATES_ANALYZED.pkl --color "X" --saveLoc D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_C_2D\FIGURES\STATS\
python abm_stats.py D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_CH_2D\DATA\SUBSETS\ANALYZED\VITRO_DISH_TREAT_CH_2D_X_X_X_X_X_STATES_ANALYZED.pkl --color "X" --saveLoc D:\Users\Alex\Documents\Northwestern\Research\ABM\Output\VITRO_DISH_TREAT_CH_2D\FIGURES\STATS\

read